CREATE TABLE `audit` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `datetime_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user` VARCHAR(45) NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8